### ISSUE TITLE
Installation section

### ISSUE THREAD

**Issue by lfarah** [FlexMonkey/Blurable#6]
Hey, your library is really interesting.

The only problem I found was the `README.md`, which lacks an `Installation Section`
I created this [iOS Open source Readme Template](https://github.com/awesome-labs/iOS-readme-template) so you can take a look on how to easily create an `Installation Section`
If you want, I can help you to organize the lib.

What are your thoughts? 😄

**Comment by FlexMonkey** [comment]
Hi Lucas,

Apologies for the delay in responding - I've been away on holiday. I like you template! I'm really busy at the moment, if you have time to organize the library, I'd appreciate the assistance :)

Simon
