### ISSUE TITLE
Blur Background Image only

### ISSUE THREAD

**Issue by avdeguzman** [FlexMonkey/Blurable#8]
Hi, I have a big UIImageView which serves as a background, and a small UIImageView which will serve as the profile picture, displayed in front of the background.

I wanted the background UIImageView to be blurred. I used Blurable. While it worked, but then however the small UIImageView intended for the profile picture disappeared. Is this a bug?

**Comment by avdeguzman** [comment]
Fixed my own issue. I kind of observed that the small UIImageView went BACK of the now-blurred background UIImageView.

To fix this, I put my small UIImageView in a different UIView, then called this after the blur function:

`self.view.bringSubviewToFront(self.viewProfilePicture)`

**Comment by avdeguzman** [comment]
Well, not sure if what I did was a hack, or if is there a bug or none, or whether I'm not just implementing it correctly. So even if I had fixed it in my end, I'll still look forward you shedding some light on this. :) Thanks!

**Comment by FlexMonkey** [comment]
Hi, if you're just blurring an image, you probably don't want to use this code. Simply blur the image with a CoreImage filter and display that.
